version: '3.4'

services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/chat-api:latest
    env_file:
      - ./.env.backend
      - ./.env.test
    volumes:
      - prisma:/app/prisma

  nginx:
    image: nginx:1.25.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    command: [nginx-debug, '-g', 'daemon off;']

volumes:
  prisma:
