name: CI

on:
  pull_request:

jobs:
  validate_nginx:
    runs-on: ubuntu-latest
    services:
      backend:
        image: nginx:1.25.4
        ports:
          - 4000:80
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm -i -v ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro nginx:1.25.4 nginx -t
