name: CI

on:
  pull_request:

jobs:
  validate_nginx:
    runs-on: ubuntu-latest
    services:
      backend:
        image: nginx:1.25.4
        ports:
          - 4000:80
    container: nginx:1.25.4
    steps:
      - uses: actions/checkout@v4
      - run: nginx -c ./nginx/nginx.conf -t
