name: CI

on:
  pull_request:

jobs:
  validate_nginx:
    runs-on: ubuntu-latest
    services:
      backend:
        image: nginx:1.25.4
        ports:
          - 4000:80
    container: nginx:1.25.4
    steps:
      - uses: actions/checkout@v4
      - run: cp ./nginx/nginx.conf /etc/nginx/nginx.conf
      - run: nginx -t

  validate_docker_compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose config
