name: CI

on:
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  validate_nginx:
    runs-on: ubuntu-latest
    services:
      backend:
        image: nginx:1.25.4
        ports:
          - 4000:80
    container: nginx:1.25.4
    steps:
      - uses: actions/checkout@v4
      - run: cp ./nginx/nginx.conf /etc/nginx/nginx.conf
      - run: nginx -t

  validate_docker_compose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: touch .env.backend
      - run: envsubst < docker-compose.yml > docker-compose.ci.yml
      - run: docker compose -f docker-compose.ci.yml config
        env:
          DOCKERHUB_USERNAME: DOCKERHUB_USERNAME

  trigger_create_deployment:
    uses: ./github/workflows/create-deployment.yml@d10cad59435cf7928d1b379958f212ecbc78df48
    secrets: inherit
