on:
  workflow_call:
    secrets:
      DISPATCH_PAT:
        required: true

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.repos.createDispatchEvent({
              owner: '${{ github.repository_owner }}',
              repo: 'chat-deployment',
              event_type: 'deploy',
            });
            console.log(result)
            console.log(`Target Job URL: ${process.env.GITHUB_SERVER_URL}/${{ github.repository_owner }}/chat-deployment/actions/runs/${result.data.id}`);

          github-token: ${{ secrets.DISPATCH_PAT }}
