on:
  workflow_call:
    secrets:
      DISPATCH_PAT:
        required: true

jobs:
  start-deployment:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in other repository
        uses: actions/github-script@v6
        with:
          script: |
            const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

            try {
              await github.rest.repos.createDispatchEvent({
                owner: '${{ github.repository_owner }}',
                repo: 'chat-deployment',
                event_type: 'deploy',
              });

              let runStatus = 'queued';
              let runConclusion;

              while (runStatus !== 'completed') {
                const runs = await github.rest.actions.listWorkflowRunsForRepo({
                  owner: '${{ github.repository_owner }}',
                  repo: 'chat-deployment',
                  event: 'repository_dispatch',
                  per_page: 1,
                });

                runStatus = runs.data.workflow_runs[0].status;
                console.log(`Workflow run status: ${runStatus}`);

                if (runStatus !== 'completed') {
                  await sleep(5000); // wait for 5 seconds before checking the status again
                } else {
                  runConclusion = runs.data.workflow_runs[0].conclusion;
                }
              }

              if (runConclusion !== 'success') {
                throw new Error(`Workflow did not end in success. Conclusion: ${runConclusion}`);
              }
            } catch (error) {
              console.error('Error:', error);
            }

          github-token: ${{ secrets.DISPATCH_PAT }}
