name: Deploy

on:
  push:
    branches:
      - main

  repository_dispatch:
    types: ['deploy']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo DATABASE_URL=$DATABASE_URL >> .env.backend
          echo JWT_SECRET=$JWT_SECRET  >> .env.backend
          echo JWT_EXPIRATION_TIME=$JWT_EXPIRATION_TIME >> .env.backend
          echo RESEND_API_KEY=$RESEND_API_KEY  >> .env.backend
          echo BACKEND_DOMAIN=$BACKEND_DOMAIN  >> .env.backend
          echo JWT_SECRET_FORGOT_PASSWORD=$JWT_SECRET_FORGOT_PASSWORD  >> .env.backend
          echo JWT_EXPIRATION_TIME_FORGOT_PASSWORD=$JWT_EXPIRATION_TIME_FORGOT_PASSWORD  >> .env.backend
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          source: docker-compose.yml,.env.backend,.env.test,nginx
          target: /${{ secrets.VM_USERNAME }}
          timeout: 120s
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_PRIVATE_KEY }}
          script: docker compose up -d --force-recreate
