on:
  workflow_call:
    secrets:
      DISPATCH_PAT:
        required: true

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    needs:
      - docker_build_push
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in other repository
        uses: actions/github-script@v6
        with:
          script: |
            const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

            await github.rest.repos.createDispatchEvent({
              owner: '${{ github.repository_owner }}',
              repo: 'chat-deployment',
              event_type: 'deploy',
            });


            let runStatus = 'queued';
            while (runStatus !== 'completed') {
              const runs = await github.rest.actions.listWorkflowRunsForRepo({
                owner: '${{ github.repository_owner }}',
                repo: 'chat-deployment',
                event: 'repository_dispatch',
                per_page: 1,
              });

              runStatus = runs.data.workflow_runs[0].status;
              console.log(`Workflow run status: ${runStatus}`);

              if (runStatus !== 'completed') {
                await sleep(5000); // wait for 5 seconds before checking the status again
              }
            }

            const runConclusion = runs.data.workflow_runs[0].conclusion;
            if (runConclusion !== 'success') {
              throw new Error(`Workflow did not end in success. Conclusion: ${runConclusion}`);
            }
          github-token: ${{ secrets.DISPATCH_PAT }}
